### ISSUE TITLE
stuck at "Executing payload"

### ISSUE THREAD

**Issue by kinkenyuen** [synackuk/n1ghtshade#4] opened 2019-12-10 13:37 UTC
Boot Tethered rate is low, stuck at "Executing payload"

iPhone 5,2 iOS 7.1.2

MacOS 10.15

**Comment by NotHereForTheDong** [comment] 2019-12-10 22:26
I have an iPhone 5,1
iOS 7.1.2
MacOS 10.14.6
Executing payload many times over (40 tries) before it works

and if I run ipwndfu -p && ipwndfu --l unpacked iBSS
and unplug then:
 irecovery -f iBSS.*
irecovery -f iBEC.*
irecovery -s
/send applelogo*
setpicture
bgcolor 0 0 0
/send DeviceTree.*
devicetree
/send kernelcache.*
bootx

it boots up no problem so I'm sure the issue is not my computer as doing all components manually for booting does work

**Comment by synackuk** [comment] 2019-12-13 22:21
@kinkenyuen and @NotHereForTheDong Can you run from terminal with LIBUSB_DEBUG=3 environment variable set?

**Comment by NotHereForTheDong** [comment] 2019-12-15 01:26
@synackuk 

![087BD36C-5D9D-4054-A7E7-BAA15F992941](https://user-images.githubusercontent.com/52018850/70856733-fc58a780-1eaf-11ea-8bc3-5513e2a362b0.jpeg)


I always get (Darwin_claim_interface) USBinterFaceOpen : Another process has device open for exclusive access.

If I use irecovery to reset the connection until that output is gone and it’s just left with waiting for DFU device, it greatly improves the success rate.

I think that libUSB doesn’t close the connection properly not allowing for any IOsurface to be available.

**Comment by TXIuTnVsbA** [comment] 2019-12-16 04:00
我也是中了这个问题，一直卡在那个什么界面，系统内核占用了usb端口，然后就卡住，然后就闪退了
= =我只知道是这app的线程问题

**Comment by synackuk** [comment] 2019-12-23 01:15
@NotHereForTheDong I think the success rate should be greatly improved with beta 12.

**Comment by synackuk** [comment] 2020-01-06 03:53
Closing as duplicate of #23

**Closed by synackuk** 2020-01-06 03:53 UTC
