### ISSUE TITLE
iPhone 5c A1532 and A1456 both stuck at executing payload

### ISSUE THREAD

**Issue by appletech752** [synackuk/n1ghtshade#12] opened 2019-12-13 07:26 UTC
I tried booting, jailbreaking, restoring... used every iOS 7 ipsw and three different devices. It always gets stuck on executing payload.

Working great on the iPhone 5 but I haven't seen anyone get the 5c working.

I have concluded that the iPhone 5c is unsupported unless anyone says otherwise.

**Comment by synackuk** [comment] 2019-12-13 22:17
5c, GSM or global?

**Comment by appletech752** [comment] 2019-12-13 22:21
GSM

**Comment by appletech752** [comment] 2019-12-13 22:23
I’ve now attempted it 20+ times on five different GSM 5c devices

**Comment by synackuk** [comment] 2019-12-13 22:27
@appletech752 What macOS?

**Comment by appletech752** [comment] 2019-12-13 22:27
Occasionally (about 1 in 10 times) it goes through but it then gets stuck at the libbelladonna “failed to restore device” error. See my other issue

**Comment by appletech752** [comment] 2019-12-13 22:27
High sierra

**Comment by synackuk** [comment] 2019-12-13 22:28
Right, I will play with High Sierra now.

**Comment by synackuk** [comment] 2019-12-23 01:13
@appletech752 Please try beta 12.

**Comment by Merculous** [comment] 2019-12-23 05:18
I am also unable to restore my 5C iPhone5,3 to any iOS. Still an issue in B12.

**Comment by synackuk** [comment] 2020-01-06 03:49
Closing as duplicate of #23

**Closed by synackuk** 2020-01-06 03:49 UTC
