### ISSUE TITLE
Executing payload

### ISSUE THREAD

**Issue by TXIuTnVsbA** [synackuk/n1ghtshade#14] opened 2019-12-14 09:54 UTC
Process:               n1ghtshade [16833]
Path:                  /private/var/folders/*/n1ghtshade.app/Contents/MacOS/n1ghtshade
Identifier:            com.synackuk.n1ghtshade
Version:               0.01 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           n1ghtshade [16833]
User ID:               501

Date/Time:             2019-12-14 17:50:46.808 +0800
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Anonymous UUID:        056AFB29-77A6-41D2-9C0B-ACEB13E21521

Time Awake Since Boot: 1000 seconds

System Integrity Protection: disabled

Notes:                 Translocated Process

Crashed Thread:        2  Dispatch queue: com.apple.root.user-initiated-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [16833]
VM Regions Near 0:
--> 
    __TEXT                 000000010b55c000-000000010b7a1000 [ 2324K] r-x/rwx SM=COW  /var/folders/*/n1ghtshade.app/Contents/MacOS/n1ghtshade

**Comment by TXIuTnVsbA** [comment] 2019-12-14 09:57
Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff70848166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff708486cc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff393bf36b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff393be907 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff393bdfe3 CFRunLoopRunSpecific + 499
5   com.apple.HIToolbox           	0x00007fff37f4567d RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff37f453bd ReceiveNextEventCommon + 600
7   com.apple.HIToolbox           	0x00007fff37f45147 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff365ca864 _DPSNextEvent + 990
9   com.apple.AppKit              	0x00007fff365c95d4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  com.apple.AppKit              	0x00007fff365c3d76 -[NSApplication run] + 658
11  com.synackuk.n1ghtshade       	0x000000010b58ab9a 0x10b55c000 + 191386
12  libdyld.dylib                 	0x00007fff706ff2e5 start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff70848166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff708486cc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff393bf36b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff393be907 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff393bdfe3 CFRunLoopRunSpecific + 499
5   com.apple.AppKit              	0x00007fff365d1dba _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff7090bd36 _pthread_start + 125
7   libsystem_pthread.dylib       	0x00007fff7090858f thread_start + 15

Thread 2 Crashed:: Dispatch queue: com.apple.root.user-initiated-qos
0   libusb-1.0.0.dylib            	0x000000010b9b83d1 darwin_reset_device + 523
1   com.synackuk.n1ghtshade       	0x000000010b5611f8 0x10b55c000 + 20984
2   com.synackuk.n1ghtshade       	0x000000010b55fe6b 0x10b55c000 + 15979
3   com.synackuk.n1ghtshade       	0x000000010b55e032 0x10b55c000 + 8242
4   com.synackuk.n1ghtshade       	0x000000010b58b3e7 0x10b55c000 + 193511
5   libdispatch.dylib             	0x00007fff706ae583 _dispatch_call_block_and_release + 12
6   libdispatch.dylib             	0x00007fff706af50e _dispatch_client_callout + 8
7   libdispatch.dylib             	0x00007fff706bd933 _dispatch_root_queue_drain + 663
8   libdispatch.dylib             	0x00007fff706bdf22 _dispatch_worker_thread2 + 92
9   libsystem_pthread.dylib       	0x00007fff709086d5 _pthread_wqthread + 220
10  libsystem_pthread.dylib       	0x00007fff7090857b start_wqthread + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff7090856c start_wqthread + 0

Thread 4:: org.libusb.device-hotplug
0   libsystem_kernel.dylib        	0x00007fff70848166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff708486cc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff393bf36b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff393be907 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff393bdfe3 CFRunLoopRunSpecific + 499
5   com.apple.CoreFoundation      	0x00007fff393bddba CFRunLoopRun + 40
6   libusb-1.0.0.dylib            	0x000000010b9b9670 darwin_event_thread_main + 398
7   libsystem_pthread.dylib       	0x00007fff7090bd36 _pthread_start + 125
8   libsystem_pthread.dylib       	0x00007fff7090858f thread_start + 15

Thread 2 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000ef634c0  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x000070000ef63560  rsp: 0x000070000ef634c0
   r8: 0x0000000000001a97   r9: 0x0000000000000000  r10: 0x00000000000010bc  r11: 0x0000000000000206
  r12: 0x000000010fde4000  r13: 0x0000000000000001  r14: 0x0000000000000000  r15: 0x00006000027cae60
  rip: 0x000000010b9b83d1  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     1
Error Code:      0x00000004 (no mapping for user data write)
Trap Number:     14

**Comment by synackuk** [comment] 2019-12-23 01:13
@TXIuTnVsbA I don't understand what the error is.

**Comment by synackuk** [comment] 2020-01-06 03:48
Closing as title is duplicate of #23

**Closed by synackuk** 2020-01-06 03:48 UTC
